version: 2
updates:
  # Enable version updates for npm (includes pnpm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Group similar updates together
    groups:
      # Group all Radix UI updates
      radix-ui:
        patterns:
          - "@radix-ui/*"
      # Group React-related updates
      react:
        patterns:
          - "react*"
          - "@types/react*"
      # Group development dependencies
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "typescript"
          - "eslint*"
          - "prettier*"
      # Group build tools
      build-tools:
        patterns:
          - "next"
          - "tailwindcss*"
          - "postcss*"
          - "autoprefixer"
      # Group database and backend
      backend:
        patterns:
          - "@supabase/*"
          - "pg*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"
